name: ams2025-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - sphinx-pythia-theme
  - cartopy
  - matplotlib
  - numpy
  # - pyrad_arm
  - wradlib
  - pydda
  - zarr
  - xradar>=0.6.3
  - python<=3.11
  - metpy # needed for pyrad example
  # this is needed for gpm-api
  - gpm-api>=0.3.1
  - pycolorbar>=0.1.0
  - ximage>=0.0.5
  - shapely>=2.0.0
  - geopandas
  - xoak
  - scikit-learn
  - folium
  - fsspec
  - s3fs
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - libaec
  - coreutils
  - autoconf
  - automake
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
  # this is needed for notebooks
  - zip
  # debugging
  - sphinx>=7.4.7
  - sqlite>=3.46.0
  # mystmd
  - mystmd
  - ipykernel
  - pytest
  - pytest-xdist
  # this is needed for PyDDA performance
  - jaxopt
  - tensorflow>=2.6
  - tensorflow-probability>=0.24
  # interactive plotting
  - hvplot
  - datashader
  # needed for wradlib
  - bottleneck
  - rioxarray
  # needed for LROSE / pyrad
  - metpy
  - jupyterlab_rise
  - plotly
  - tobac
  # needed for ARCO datasets
  - xarray>=2025.08.0
  - icechunk>=1.1.3
  - seaborn
  - pip
  - pip:
    - arm_pyart>=2.0.0
